- name: Checkit UX Recommendations
  img: https://farm6.staticflickr.com/5590/15048102369_3dd8eff4e4_o.png
  imgalt:
  description: Checkit is a smart monitoring system by Elektron Technology for food safety and enforcing HACCP compliance. It entails a range of temperature sensors and dashboards to allow food workers to respond to alters.
  role: Work with Elektron as a usecase to inform the Xively product, whilst providing recommendations for the next phase of Checkit dashboards.

- name: Xi Glass Demo
  img: https://farm6.staticflickr.com/5590/15048102369_3dd8eff4e4_o.png
  imgalt:
  description: Using google glass to control a xively connected tank for tradeshow demonstrations. The tank was able to refill and drain. The challenge of designing the glass ui for this demo was to communicate the current state of the tank and which actions were active.
  role: This was a short project working with the Xively Services team, including a couple of iterations until the final implementation. My role was to define the flow and the different states as well as design the ui.
  achievements:
    - designing glass demo in short time-frame
    - working across time zones
    - tank demo was used as key demonstration at trade shows to communicate potential use cases for xively

- name: Connected commercial printers
  img: https://farm6.staticflickr.com/5590/15048102369_3dd8eff4e4_o.png
  imgalt:
  description: How to
  role: Working with the Xi Services Team as Lead Designer, coordinating the work of visual designers and front-enders.

- name: Internet of School Things
  img: https://farm6.staticflickr.com/5590/15048102369_3dd8eff4e4_o.png
  imgalt:
  description: Internet of School things is a … How to allow school kids to easily provide access to sensor data whilst
  role: Defining early wireframes and flows.
  achievements: Has been trialed in X schools
  link: http://portal.iotschool.org/

- name: Salesforce call assistant dashboard
  img: https://farm6.staticflickr.com/5590/15048102369_3dd8eff4e4_o.png
  imgalt:
  description: Providing a better UI integrated into salesforce to allow sales assistants to manage leads and follow up on new opportunities to meet their daily quota.
  role: Working with the Xi Services team to provide UX and UI recommendations on how to improve the usability of one of their consulting deliverables. Time management to meet the allocated time of visual designer and checking meetings. As we were involved rather late in the project, I focused on only a handful of ux and ui recommendations that would add a maximum positive impact.

- name: Current Cost Dashboard
  img: https://farm6.staticflickr.com/5590/15048102369_3dd8eff4e4_o.png
  imgalt:
  description: Simple responsive webapp dashboard which let's users see their home energy usage when ever they wish.
  role: ux and visual design
